name: workflow trigger with user input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'In which Environment we want to deploy our code'
        required: true
        default: 'dev'
        type: choice
        options:
          - production
          - qa
          - dev 
          - uat 


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying to ${{ github.event.inputs.environment }} Environment'



